import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  const [dialogIsOpen, setDialogIsOpen] = useState(false)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="container">
        <ul className="flex list-none">
          <li className="flex-auto">ronsj.dev</li>
          <li className="flex-initial">
            <button onClick={() => setDialogIsOpen(!dialogIsOpen)}>
              [Menu]
            </button>
          </li>
        </ul>
      </nav>
      <main className="container md:mx-auto">
        <h1 className="text-6xl font-bold underline">Hey 👋 I&apos;m Ron! </h1>
        <h2 className="text-3xl">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt
          dolor sint vitae, ab eaque est suscipit iure nobis! Nobis repudiandae
          quam id quos.
        </h2>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, iste
          id possimus ad odit maiores beatae molestiae sapiente, illum quam
          dignissimos itaque qui? Accusamus, dolore. Quibusdam veniam commodi
          quas aut? Odit explicabo, ad nostrum velit nemo obcaecati vitae
          accusamus sapiente dignissimos. Molestiae fugiat fugit doloribus saepe
          tempore illo libero debitis in, dicta exercitationem. Id voluptas
          maxime excepturi praesentium quia dolor?
        </p>
        <p>
          <a href="#">Resume</a>
        </p>
        <p>
          <a href="#">LinkedIn</a>
        </p>
        <p>
          <a href="#">GitHub</a>
        </p>

        <h3>Blog</h3>
        <ul className="list-none">
          <li>1</li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
          <li>5</li>
        </ul>
      </main>
      <footer className="container">
        <ul className="flex list-none">
          <li className="flex-auto">ronsj.dev</li>
          <li className="flex-initial">[Socials]</li>
        </ul>
      </footer>
      <dialog open={dialogIsOpen} style={{ border: '1px solid red' }}>
        test
      </dialog>
    </div>
  )
}

export default Home
