import type { NextPage } from 'next'
import Head from 'next/head'

export function getStaticProps() {
  return {
    props: {},
  }
}

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Ron</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>👋 Hey!</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod ipsa ut
        minus modi voluptas deleniti alias! Voluptas, delectus reprehenderit
        adipisci sapiente doloremque, nostrum enim est aliquam doloribus,
        commodi provident consequatur.
      </p>
    </main>
  )
}

export default Home
